### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sledorze** [Randonee/Basis#1]
Run command "ant haxelib"
should be 
Run command "ant buildHaxelib"

**Comment by Randonee** [comment]
Thanks.
It should actually be "testlib" which will build and install.
This has been updated in: https://github.com/Randonee/Basis/commit/67b42fe90fe4765a832a89faedafc82f5ee326be

**Comment by sledorze** [comment]
Ok, works :)

However, trying to run the examples like so:

haxelib run Basis build.xml apple

fails with output:

haxelib run Basis build.xml apple
/usr/lib/haxe/lib/BasisApple/0,0,2/apple/ui/UIBarButtonItem.hx:4:
characters 0-28 : Class not found : ios.UIBarItemManager
haxe/example/ApplicationMain.hx:9: characters 2-27 : basis.ios.#ViewManager
has no field addToRootView
/usr/lib/haxe/lib/BasisApple/0,0,2/basis/ios/ViewBase.hx:22: characters
9-31 : basis.ios.#ViewManager has no field createView
haxe/example/MainView.hx:41: characters 2-37 : apple.ui.UINavigationBar has
no field createNavigationItem
haxe/example/MainView.hx:42: characters 2-29 : apple.ui.UINavigationBar has
no field setItemTitle
haxe/example/MainView.hx:46: characters 20-41 : apple.ui.UIBarButtonItem
does not have a constructor
...

On Wed, Feb 13, 2013 at 9:34 PM, Aaron notifications@github.com wrote:

> Thanks.
> It should actually be "testlib" which will build and install.
> This has been updated in: 67b42fehttps://github.com/Randonee/Basis/commit/67b42fe90fe4765a832a89faedafc82f5ee326be
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Randonee/Basis/issues/1#issuecomment-13516603.

## 

Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by Randonee** [comment]
This has been fixed in: https://github.com/Randonee/BasisApple/commit/7824fbf9a878e1824e2f2004b8462f4d8b39a3b7
An import was pointing to a file that was no longer used.
I'll updated the build script to remove all haxelib old haxelib files before installing so this no longer happens.

**Comment by sledorze** [comment]
Awesome, works beautifully.

**Comment by Randonee** [comment]
Thanks!
I've also just pushed a change so that BasisApple and BasisAndroid are no longer installed when installing Basis. They must now be installed separately. Having Basis install them was causing too many headaches.

https://github.com/Randonee/Basis/commit/5357862076c71f37927694b46086da835add80fc
https://github.com/Randonee/BasisApple/commit/3b65c258776b2bc6f63fea2498ce78e95cd700b2
https://github.com/Randonee/BasisAndroid/commit/815659ef6870412ca27426d016259fe8aecce5d1
