### ISSUE TITLE
Development with Build system.

### ISSUE THREAD

**Issue by sledorze** [Randonee/Basis#2]
Is there a documentation on how to customize the build.xml file in the example? (adding lib for instance)

Also, I'm using SublimeText and it is looking for a hxml file to find compilation information to provide completion.
It would be handy to generate a hxml file so that IDEs can take advantage of this.

**Comment by Randonee** [comment]
I've added some documentation to the Basis read me. I'll find a better location for it later but this should be a good start.
https://github.com/Randonee/Basis/commit/867b2a43d8acaa9f1ea55b1cd77a49a5bceb5ae1

hxml is specific to the haxe compiler and a different format. I could see using another extension. Maybe .basis?

**Comment by sledorze** [comment]
I was not saying you should end your config files with hxml.
The point is that the IDE will look for a .hxml file, so it would be nice to derive one from you definition file.

**Comment by Randonee** [comment]
got it. Do you know how NME handles this?

**Comment by sledorze** [comment]
Actually, NME is already so popular that IDEs cope with it.
for instance see usage here:
https://github.com/clemos/haxe-sublime2-bundle

On Wed, Feb 13, 2013 at 11:35 PM, Aaron notifications@github.com wrote:

> got it. Do you know how NME handles this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Randonee/Basis/issues/2#issuecomment-13522522.

## 

Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by Randonee** [comment]
A command could be added to output an hxml file for a given target.
Something like: "haxelib run basis -hxml apple.hxml apple"
Where apple.hxml is the file name and apple is the target name.
Is that what you are looking for?

**Comment by sledorze** [comment]
that s a good way to achieve it indeed
