### ISSUE TITLE
Obj-C target and Basis

### ISSUE THREAD

**Issue by fullofcaffeine** [Randonee/Basis#4]
Hi,

I'm very interested in Basis, but I dislike the fact it needs CFFI and C++ as of now. I've been playing with the Obj-C target today and was able to compile all the samples as well as some small experiments.

Baluta also has the hxcocoa lib. I was wondering what would it take to convert Basis to  Obj-C now and then patch the compiler as we find issues?

I'm more than willing to collaborate. I think Basis+Haxe ObjC would yet another killer "app" for Haxe, a much needed target + framework in fact!

If you're interested, let's connect on Google Talk (boss@fullofcaffeine.com) or Skype (celoserpa). I'd love to help.

**Comment by Randonee** [comment]
I agree. The current BasisApple is not the best approach and using a haxe objc target would be ideal. It may also be worth waiting for the haxe C target to be finished as it will probably be easier to interface with obj c.

**Comment by fullofcaffeine** [comment]
Thank you for replying.

I had some success using the hxobjc target so far, but well, mainly sample apps.

Do you use Basis for real-world projects? How was your experience with it? I'd love a solution that allowed me to use Haxe for two reasons:

1) I don't quite like Objective-C
2) Potential to abstract stuff and share code between targets (in theory making it easier to port the app to Android for example)

**Comment by Randonee** [comment]
Basis was used for some in house projects.

Apple just released swift. Looks much easier to create a haxe target for.
https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/LandingPage/index.html
