### ISSUE TITLE
Any chance of this being updated to work with newer haxe?

### ISSUE THREAD

**Issue by NicoM1** [Randonee/Basis#5]
As title, build fails with macro issues, I'm assuming its due to this being outdated,

thanks,
Nico

**Comment by Randonee** [comment]
Yeah, I'll take a look once 3.2 is released. (I'm assuming your referring to 3.2 builds)

**Comment by Randonee** [comment]
@NicoM1 what is giving you macro errors?

**Comment by NicoM1** [comment]
huh, can't get it to build at all now, was having this before and don't remember what I did, it just says the build file wasn't found when I try to build the example, I had this before and I coaxed it into finding it somehow but I don't remember.....

**Comment by NicoM1** [comment]
ok, so got it to build, had to use ./build.basis instead of build.basis (using cmder on windows, maybe related?) and here is the output:

![](http://i.imgur.com/sjtYesS.png)

**Comment by Randonee** [comment]
are you using the latest code from git?

**Comment by NicoM1** [comment]
I think I'm using the haxelib version, will try latest code tomorrow

**Comment by NicoM1** [comment]
And if you mean haxe then no, 3.2 build

**Comment by Randonee** [comment]
the haxelib hasn't been updated in a while. Try the latest basis code from git.
